# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logito < Formula
  desc "Developer-first runtime review logging CLI."
  homepage "https://progadigital.com"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v0.1.3/logito_0.1.3_darwin_amd64.tar.gz"
      sha256 "0ecea75d537fce6b1abe78f455ab7bd66841f1939168a4fcbcd1a0ef90c83c57"

      define_method(:install) do
        bin.install "logito"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v0.1.3/logito_0.1.3_darwin_arm64.tar.gz"
      sha256 "7ad71baa1c86388cdf8eacd7b527f748842f7438c67f227ed33390613d3e0c2f"

      define_method(:install) do
        bin.install "logito"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v0.1.3/logito_0.1.3_linux_amd64.tar.gz"
      sha256 "233a3b76a1b2c894987a05e07ba8cc358a21d3699ef881e987cced1d407e2bfb"
      define_method(:install) do
        bin.install "logito"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v0.1.3/logito_0.1.3_linux_arm64.tar.gz"
      sha256 "7028545e7e3027a298fb426ec11e5df6bddf63afe091212b2817280cf622e45d"
      define_method(:install) do
        bin.install "logito"
      end
    end
  end
end
