# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logito < Formula
  desc "Developer-first runtime review logging CLI."
  homepage "https://progadigital.com"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v0.1.4/logito_0.1.4_darwin_amd64.tar.gz"
      sha256 "153c31b365f8fcce7d6d65f7abcdf14565ab7a5dfe56964a3197ff611d670088"

      define_method(:install) do
        bin.install "logito"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v0.1.4/logito_0.1.4_darwin_arm64.tar.gz"
      sha256 "83cbaebc38be65b9044314217d474570dc3dd99984bd336c234bf586a3091cdb"

      define_method(:install) do
        bin.install "logito"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v0.1.4/logito_0.1.4_linux_amd64.tar.gz"
      sha256 "f3d299f862793e0aae3abd398c024dfb237a4247fc9a1b4a7bd9911edae511fe"
      define_method(:install) do
        bin.install "logito"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v0.1.4/logito_0.1.4_linux_arm64.tar.gz"
      sha256 "cb3a9af76477ddc49df21355796af458126d78fd2bf3f104e7fcae70d62b6165"
      define_method(:install) do
        bin.install "logito"
      end
    end
  end
end
