# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logito < Formula
  desc "Runtime debugging CLI. Capture, compare, and review system behavior."
  homepage "https://logito.app"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v1.1.0/logito_1.1.0_darwin_amd64.tar.gz"
      sha256 "2757aaaa489d6528edff3a001195d1f8dd84c8a6cbbdbc32ece4a2e99a333e01"

      define_method(:install) do
        bin.install "logito"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v1.1.0/logito_1.1.0_darwin_arm64.tar.gz"
      sha256 "503b2ff432e037eb7ff7fe6318e71df6c223a28891c295670f8c0a143e7d9d65"

      define_method(:install) do
        bin.install "logito"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v1.1.0/logito_1.1.0_linux_amd64.tar.gz"
      sha256 "8e237c86a1532472dfb6b68777c6361db89cf578a9ba6ba1bfdb991e54041e2f"
      define_method(:install) do
        bin.install "logito"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v1.1.0/logito_1.1.0_linux_arm64.tar.gz"
      sha256 "7cae43b9cf447ecbc3a3d3f0478281a470b41fa936de54c58b337411dde4bd47"
      define_method(:install) do
        bin.install "logito"
      end
    end
  end
end
