# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logito < Formula
  desc "Runtime debugging CLI. Capture, compare, and review system behavior."
  homepage "https://logito.app"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v1.1.1/logito_1.1.1_darwin_amd64.tar.gz"
      sha256 "6ce243470123807dc672cf291928872e96dd8a1b27dd3e17256f3b93137a5684"

      define_method(:install) do
        bin.install "logito"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v1.1.1/logito_1.1.1_darwin_arm64.tar.gz"
      sha256 "5502041e9699e8ca66687ff0ff3b721bf1a3a172d4cbb1ea3ab1f84048d0db81"

      define_method(:install) do
        bin.install "logito"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v1.1.1/logito_1.1.1_linux_amd64.tar.gz"
      sha256 "2b40382777a9ac4e19b680e3d78c6409b5019d9d34be88870658926f59a9eba3"
      define_method(:install) do
        bin.install "logito"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/progadigital/homebrew-tap/releases/download/v1.1.1/logito_1.1.1_linux_arm64.tar.gz"
      sha256 "2c4c6838b621c782cdc6c9cea2de9bd4990fe9dbe1fb9d281ab7ccb95a9d7a7c"
      define_method(:install) do
        bin.install "logito"
      end
    end
  end
end
